src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 * @Vich\Uploadable
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isOnline;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="projects")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ProposePar;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="projects", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Participant", mappedBy="project", orphanRemoval=true)
     */
    private $participants;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->setCreatedAt(new \DateTime);
        $this->setUpdatedAt(new \DateTime);
        $this->setIsOnline(true);
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsOnline(): ?bool
    {
        return $this->isOnline;
    }

    public function setIsOnline(bool $isOnline): self
    {
        $this->isOnline = $isOnline;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getProposePar(): ?User
    {
        return $this->ProposePar;
    }

    public function setProposePar(?User $ProposePar): self
    {
        $this->ProposePar = $ProposePar;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTime();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setProject($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getProject() === $this) {
                $participant->setProject(null);
            }
        }

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;


class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('imageFile',VichFileType::class)
           // ->add('isOnline')
           // ->add('createdAt')
           // ->add('updatedAt')
            ->add('tags')
            ->add('category')
           // ->add('ProposePar')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
            // supprimer le titre du formulaire
            'label'=>false
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Participant;
use App\Entity\Project;
use App\Form\ParticipantType;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProjectController extends AbstractController
{

    private $projectRepository;

    public function __construct(ProjectRepository $projectRepository)
    {
        $this->projectRepository = $projectRepository;
    }

    /**
     * @Template()
     * @Route("/projects", name="projects")
     */
    public function index()
    {
        // SELECT * FROM projects
        $projects = $this->projectRepository->findAll();
        return ['projects'=>$projects];
    }

    /**
     * @Route("/project/add", name="project_add")
     */
    public function add(Request $request){
        // création de l'objet à persister dans la db
        $project = new Project();
        // création de l'objet form qui va générer le html dans la vue et prendre en charge la validation du formulaire et hydratation de l'objet $project avec les données de la saisie dans le formulaire
        $project->setProposePar($this->getUser());

        // dd($request->files->get('project')); // équivaut à dd($_FILES['project']);


        // création de l'objet form
        $form = $this->createForm(ProjectType::class, $project);
        // hydratation de l'objet avec les datas du formulaire (objet request)
        $form->handleRequest($request);

        // si validation du formulaire et formulaire valide :
        if ($form->isSubmitted() && $form->isValid()){

            $fichier = $request->files->get('project');
            $extensions_allowed = ['image/jpeg','image/png','image/gif'];
            $fichier_name = $fichier['imageFile']['file'];
            $mime_type = $fichier_name->getMimeType();

            if(!in_array($mime_type,$extensions_allowed)){
                $this->addFlash('error','extension non autorisée');
                return $this->redirectToRoute('project_add');
            }

            // associer le nom de l'image au projet
            $project->setImageName($fichier_name->getClientOriginalName());

            // récupérer l'entity manager de Doctrine (ORM)
            $em = $this->getDoctrine()->getManager();
            // association du user loggé et du projet qu'il est en train de créer
            // enregsitrer dans la db des datas de form (équivalant de save() dans laravel
            $em->persist($project);
            $em->flush();
            // ajouter un message flash dans la session
            $this->addFlash('success','Merci ! Votre projet a été proposé au Maitre Jedi');
            // return redireciton vers page de confirmation de création du projet
            return $this->redirectToRoute('project_show');
        }


        // affichage de la vue
        return $this->render('project/add.html.twig', ['form'=>$form->createView()]);
    }

    /**
     * @Template()
     * @Route("/project/{id}", name="project_show")
     */
    public function show(Request $request){
        // return $this->render('project/show.html.twig'); -> remplacé par @Template, car tous les fichiers on été bien nommés
        // on récupère l'id dans l'url
        $project = $this->projectRepository->find($request->get('id'));

        $participant = new Participant();
        $participant->setProject($project);
        $participant->setPadawan($this->getUser());
        $participant->setStatut('en cours');
        $participant->setDateInscription(new \DateTime());

        $form = $this->createForm(ParticipantType::class, $participant);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($participant);
            $em->flush();
            $this->addFlash('success','A toi de jouer petit padawan !');
            return $this->redirectToRoute('project_show',['id'=>$project->getId()]);
        }

        // on passe le formulaire à la vue (createView() permet de générer le html du formulaire
        return ['project'=>$project,'form'=>$form->createView()];

    }
}

templates/project/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        <div class="row">
            {% if app.user %}
            <div class="col-12">
                <h4>Proposez un projet au maître Jedi</h4>
                {{ form_start(form) }}
                {{ form_errors(form) }}
                {{ form_row(form) }}
                <button class="btn btn-primary">Proposer un projet</button>
                {{ form_end(form) }}
            </div>
                {% else %}
                <div class="col-8 offset-2 text-center">
                    <h4>Vous devez être identifié pour proposer un projet au Maître Jedi</h4>
                    <img src="{{ asset('img/padawan.jpg') }}" alt="Padawan Project" class="img-fluid" width="40%">
                    <a class="btn btn-block btn-dark" href="{{ path('app_login') }}">Se connecter</a>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock body %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projets disponibles{% endblock %}

{% block body %}

<main role="main" class="container">
    <div class="row">
        <div class="container mt-8">
            <div class="album py-5">
                <div class="container">
                    <div class="row">

                        {% for project in projects %}

                        <div class="col-md-4">
                            <div class="card mb-4">
                                <img class="rounded mx-auto d-block mt-3" width="80%" src="{{ vich_uploader_asset(project, 'imageFile') }}" alt="{{ project.nom }}">
                                <div class="card-body">
                                    <h4>{{ project.nom }}</h4>

                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{{ path('project_show', {'id':project.id}) }}" class="btn btn-sm btn-outline-secondary">Voir le projet</a>

                                        </div>
                                        <small class="text-muted">5 padawans</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <main role="main" class="container">
        <div class="row">
            <div class="container mt-8">
                <div class="row">
                    <div class="col-8">
                        {# {{ dump(project) }} #}
                        <h3>{{ project.nom }}</h3>
                        <p>Projet proposé par {{ project.proposePar.prenom }} {{ project.proposePar.nom }} </p>
                        <a class="btn btn-sm btn-outline-warning mt-2 mb-2" href="">Je me lance !</a> <br>

                        {{ project.description }}

                        {% if(app.user) %}
                            <div class="text-left jumbotron">
                                <strong>Vous voulez parrticiper à ce projet ?</strong>
                                {{ form_start(form) }}
                                {{ form_row(form.githubRepository) }}
                                <button class="btn btn-primary btn-sm">Je me lance</button>
                                {{ form_end(form) }}
                            </div>
                        {% else %}
                            <a href="{{ path('app_login') }}">Connectez-vous pour participer à ce projet</a>
                        {% endif %}

                    </div>
                    <div class="col-4 text-center">
                        <img class="img-fluid" src="{{ vich_uploader_asset(project,'imageFile') }}" alt="{{ project.nom }}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <hr>
                        <h4>Padawans</h4>
                    </div>
                </div>
                <div class="row text-center">
                    {# project.participant équivaut à project->getParticipants()#}
                    {% for participant in project.participants %}
                        <div class="col-lg-1">
                            {# pas besoin d'asset dans l'image qui suit puisque c'est une url absolue et non relative #}
                            <img class="img-fluid rounded-circle" src="{{ participant.padawan.avatarGithub }}" alt="">
                            <p><a class="btn btn-outline-info btn-sm" href="{{ path('padawan_profile',{'id':participant.padawan.id}) }}" role="button">{{ participant.padawan.prenom }}</a></p>
                        </div><!-- /.col-lg-4 -->
                    {% endfor %}

                </div>

            </div>

        </div>
    </main>

{% endblock body %}